export const SIGN_IN_WITH_EMAIL = 'auth/SIGN_IN_WITH_EMAIL';
export const SIGN_IN_WITH_EMAIL_SUCCESS = 'auth/SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_IN_WITH_EMAIL_ERROR = 'auth/SIGN_IN_WITH_EMAIL_ERROR';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";